spec-kit:
  - constitution:
      path: 'CONSTITUTION.md'
      documents:
        - path: 'docs/architecture.md'
          context: 'Documents the architecture of the project and should be considered a primary source of truth.'
        - path: 'docs/ui-architecture.md'
          context: 'Documents the UI architecture of the project and should be considered a primary source of truth.'
  - specify:
      documents:
        - path: 'docs/prd.md'
          context: 'Documents the product requirements and should be considered a primary source of truth.'
        - path: 'docs/front-end-spec.md'
          context: 'Documents the front-end specifications and should be considered a primary source of truth.'
  - plan:
      documents:
        - path: 'docs/architecture.md'
          context: 'Documents the architecture of the project and should be considered a primary source of truth.'
        - path: 'docs/ui-architecture.md'
          context: 'Documents the UI architecture of the project and should be considered a primary source of truth.'
        - path: 'docs/front-end-spec.md'
          context: 'Documents the front-end specifications and should be considered a primary source of truth.'
  - tasks:
      documents:
        - path: 'docs/architecture.md'
          context: 'Documents the architecture of the project and should be considered a primary source of truth.'
        - path: 'docs/ui-architecture.md'
          context: 'Documents the UI architecture of the project and should be considered a primary source of truth.'
        - path: 'docs/front-end-spec.md'
          context: 'Documents the front-end specifications and should be considered a primary source of truth.'
  - analyze:
      documents:
        - path: 'docs/prd.md'
          context: 'Documents the product requirements and should be considered a primary source of truth, any deviations should be called out.'
        - path: 'docs/architecture.md'
          context: 'Documents the architecture of the project and should be considered a primary source of truth, any deviations should be called out.'
        - path: 'docs/ui-architecture.md'
          context: 'Documents the UI architecture of the project and should be considered a primary source of truth, any deviations should be called out.'
        - path: 'docs/front-end-spec.md'
          context: 'Documents the front-end specifications and should be considered a primary source of truth, any deviations should be called out.'
  - implement:
      documents:
        - path: 'docs/work-flow.md'
          context: 'Documents the implementation work-flow for the project and should be considered a primary source of truth.'
  - audit:
      documents:
        - path: 'docs/prd.md'
          context: 'Documents the product requirements and should be considered a primary source of truth, any deviations should be called out.'
        - path: 'docs/architecture.md'
          context: 'Documents the architecture of the project and should be considered a primary source of truth, any deviations should be called out.'
        - path: 'docs/ui-architecture.md'
          context: 'Documents the UI architecture of the project and should be considered a primary source of truth, any deviations should be called out.'
        - path: 'docs/front-end-spec.md'
          context: 'Documents the front-end specifications and should be considered a primary source of truth, any deviations should be called out.'
