extends: default

rules:
  line-length:
    max: 120
    allow-non-breakable-words: true
  indentation:
    spaces: 2
    indent-sequences: consistent
  trailing-spaces: enable
  document-start: disable
  truthy: enable
